Repository Shadows-of-Fire/Shadows-of-Greg, pull requests merged in 2021-04, with the labels that each got.

#124 Circuit assembler Config removal
  src/main/java/gregicadditions/GAConfig.java
Labels: cleanup

#126 Gregtech update
  build.gradle
  src/main/java/gregicadditions/GregicAdditions.java
  src/main/java/gregicadditions/jei/AssemblyLineInfo.java
  src/main/java/gregicadditions/jei/FusionReactor1Info.java
  src/main/java/gregicadditions/jei/FusionReactor2Info.java
  src/main/java/gregicadditions/jei/FusionReactor3Info.java
  src/main/java/gregicadditions/machines/TileEntityDrum.java
Labels: dependency

#130 Remove the buildcraft api
  build.gradle
Labels: cleanup, dependency

#131 Add assembler recipe for Assembly Line Casing
  src/main/java/gregicadditions/recipes/GARecipeAddition.java
Labels: enhancement

#132 Make drum not have a "0" NBT tag after fully emptying.
  src/main/java/gregicadditions/machines/TileEntityDrum.java
Labels: bug

#118 Machine concept for configurable wire bundling.
  src/main/java/gregicadditions/GAConfig.java
  src/main/java/gregicadditions/machines/GATileEntities.java
  src/main/java/gregicadditions/machines/TileEntityProcessingArray.java
  src/main/java/gregicadditions/recipes/GARecipeAddition.java
  src/main/java/gregicadditions/recipes/GARecipeMaps.java
  src/main/java/gregicadditions/recipes/MachineCraftingRecipes.java
  src/main/resources/assets/gtadditions/lang/en_us.lang
  src/main/resources/assets/gtadditions/lang/ru_ru.lang
  src/main/resources/assets/gtadditions/lang/zh_cn.lang
Labels: enhancement

#125 Refactor and Cleanup the lang file
  src/main/resources/assets/gtadditions/lang/en_us.lang
  src/main/resources/assets/gtadditions/lang/ru_ru.lang
  src/main/resources/assets/gtadditions/lang/zh_cn.lang
Labels: cleanup

#122 Remove Coke Oven Bricks
  src/main/java/gregicadditions/item/GAMultiblockCasing.java
  src/main/resources/assets/gregtech/models/item/metaitems/brick.coke.json
  src/main/resources/assets/gregtech/textures/blocks/casings/solid/machine_coke_oven_bricks.png
  src/main/resources/assets/gtadditions/blockstates/ga_multiblock_casing.json
Labels: cleanup

#123 Remove Glass Fiber item
  src/main/java/gregicadditions/item/GAMetaItem.java
  src/main/java/gregicadditions/item/GAMetaItems.java
  src/main/resources/assets/gregtech/models/item/metaitems/component.glass.fiber.json
Labels: cleanup

#136 Remove some unused classes
  src/main/java/gregicadditions/item/BasicMaterial.java
  src/main/java/gregicadditions/machines/SingleLimitBlockPattern.java
  src/main/java/gregicadditions/machines/SingleLimitFactory.java
  src/main/java/gregicadditions/recipes/NoEURecipeBuilder.java
Labels: cleanup
