Repository Shadows-of-Fire/Shadows-of-Greg, pull requests merged in 2021-03, with the labels that each got.

#98 Don't register materials when disabled in the config
  src/main/java/gregicadditions/GAConfig.java
  src/main/java/gregicadditions/GAEnums.java
  src/main/java/gregicadditions/item/GAMetaItem.java
  src/main/java/gregicadditions/item/GAMetaItems.java
  src/main/java/gregicadditions/recipes/GAMachineRecipeRemoval.java
  src/main/java/gregicadditions/recipes/GARecipeAddition.java
  src/main/java/gregicadditions/recipes/MachineCraftingRecipes.java
Labels: bug

#96 Cleanup duplicate material generation flags
  src/main/java/gregicadditions/GAMaterials.java
Labels: Dependency

#115 Remove Unneeded Red Alloy Recipes
  src/main/java/gregicadditions/recipes/GARecipeAddition.java
Labels: bug, dependency

#99 Cleanup ClientHandler
  src/main/java/gregicadditions/client/ClientHandler.java
  src/main/java/gregicadditions/machines/GATileEntities.java
Labels: cleanup

#117 Update GTCE dependency to 1.13.0.681
  build.gradle
  src/main/java/gregicadditions/machines/TileEntityProcessingArray.java
  src/main/java/gregicadditions/recipes/GARecipeAddition.java
  src/main/java/gregtech/api/capability/impl/MultiblockRecipeLogicWrapper.java
Labels: dependency
