Repository Shadows-of-Fire/Shadows-of-Greg, pull requests merged in 2021-05, with the labels that each got.

#133 Fix Some Recipes Being Out of Reach of CraftTweaker
  src/main/java/gregicadditions/GregicAdditions.java
  src/main/java/gregicadditions/bees/ClientProxy.java
  src/main/java/gregicadditions/bees/CommonProxy.java
  src/main/java/gregicadditions/bees/ForestryMachineRecipes.java
  src/main/java/gregicadditions/bees/GTMachineCombRecipes.java
Labels: bug

#142 Update Gregtech to 1.14.1.705
  build.gradle
Labels: dependency

#143 Fix incorrect cable recipe removals
  src/main/java/gregicadditions/recipes/GAMachineRecipeRemoval.java
Labels: bug

#149 Make the AL face the player
  src/main/java/gregicadditions/jei/AssemblyLineInfo.java
Labels: enhancement

#150 Gregtech update
  build.gradle
  src/main/java/gregicadditions/GregicAdditions.java
  src/main/java/gregicadditions/recipes/GARecipeAddition.java
Labels: dependency
